### ISSUE TITLE
Gaps in the sounds

### ISSUE THREAD

**Issue by robb** [thisisparker/mad-generation-loss#1]
I guess you noticed those annoying gaps in the end result.

My hunch is that those come from the fact that an mp3 file "rounds up" to the next full frame by padding with silence and the one second slices don't quite match up.

**Comment by thisisparker** [comment]
Switching from splitting the sound on an array to lazily using mp3splt seemed to help a bit, but there were still gaps. The new bash port of this dramatically reduces the gaps (like, almost all the way) but has some other qualities I don't love. Still trying to figure that out, but for now, 2 years later, I'm comfortable closing this issue.
